### ISSUE TITLE
Implement some sort of error handling

### ISSUE THREAD

**Issue by mohamedmansour** [mohamedmansour/google-plus-extension-jsapi#1]
This API was cooked up really quickly, there exists some error handling, but we need a more user friendly error handling. Every response should have a status indicator whether an error exists or not. That requires some plumbing again into the data but it is all good.

**Comment by nickretallack** [comment]
Yes this would be good.  I tried to use the first example in the readme but it failed on line 283 of jsapi_for_google_plus.js because dirtyCircles was undefined.  dirtyCircles is assigned to response[1], but response is just an object {"error":0, "text":"error"}.

**Comment by mohamedmansour** [comment]
@nickretallack can you please paste me the code your trying to call? Yea, it needs more plumbing for error handling, if you have any ideas, please let me know, we can try making this API more error friendly.

The working examples are in tests/api.js

**Comment by mohamedmansour** [comment]
I am adding some error handling, but needs more love.

**Comment by mohamedmansour** [comment]
Basic error handling implemented here 20438dd17a315bf6142ebf0a20d9d12dd948ce71 more needed to control the array reading.
