### ISSUE TITLE
Allow cancelling a pending request

### ISSUE THREAD

**Issue by tzafrir** [mohamedmansour/google-plus-extension-jsapi#18]
I'm looking into adding support for +mention autocomplete suggestions, and it makes sense to cancel pending requests as new characters are typed (that's how native Google+ does it).

$.ajax returns a XMLHttpRequest object, which can be .abort()-ed later - would it be enough to just return it from _requestService?

**Comment by mohamedmansour** [comment]
Yea sounds okay to me!

**Comment by tzafrir** [comment]
Fixed in ff28493cca6743caf95d40f24470aab49e8e0c27
