### ISSUE TITLE
Thanx a lot 4 ur Extended Share for Google Plus Extension

### ISSUE THREAD

**Issue by menneni** [mohamedmansour/google-plus-extension-jsapi#27]
Hello Mohamed mansour, first of all thanx 4 ur Extended Share for Google Plus plug in. its a gr8 tool.currently i am doing an academic project, developing a forum in which people post their q's n those q's have to be automatically posted on various social networking sites. i have gone through the link you provided on the site for source code but it is giiving no page error. pls help me on this issue. pls reply as  soon as possible.. thanx in advance

**Comment by mohamedmansour** [comment]
There is a example in the README let me know
