### ISSUE TITLE
xhr response problem

### ISSUE THREAD

**Issue by pennadl** [mohamedmansour/google-plus-extension-jsapi#28]
Hello, I just testing the script, I noted the _getSession function return 
_{"readyState":0,"status":0,"statusText":"Error: NETWORK_ERR: XMLHttpRequest Exception 101"}_
when https://plus.google.com is called by 

```
var xhr = $.ajax({
      type: 'GET',
      url: 'https://plus.google.com',
      data: null,
      async: false
});
```

// jsapi_for_google_plus.js , line:296

In fact the script fail the initialization in all my tests.
Any help?
Thank you

**Comment by mohamedmansour** [comment]
Have you loaded this in extension screen chrome://extensions ?  This API is for Chrome Extensions, if you wish to make it run without extensions you have to:
1. Ask the user for their user/pass
2. Emulate a login to plus.google.com save the cookies
3. For every other request, you need those cookies, call getSession

**Comment by pennadl** [comment]
Ok thanks for the tip, I had not read about the Chrome extension.
I will try this workaround to make the script work in a webView.
Stefano

**Comment by mohamedmansour** [comment]
Awesome, let me know if you need help, would be nice to have more implementations. Basically.

1) Ask the user for their user/pass 
2) Do the login to google+
3) Call getSession (make sure the cookies are persisted)
