### ISSUE TITLE
Incorrect original sharer shown for posts that have been compound shared

### ISSUE THREAD

**Issue by ryanpeggs** [mohamedmansour/google-plus-extension-jsapi#29]
If a post was shared and then the share re-shared by another user, this API returns only the previous share and not the original iteration of the post. Index 44 should be used rather than index 43 when parsing a post (~line 168).

EXAMPLE: https://plus.google.com/u/0/106518477192762767665/posts/GR8z2r6ZBuS

This api returns "john smith" as the original share owner whereas the desktop site shows "Janet HAL".

**Comment by mohamedmansour** [comment]
Can you submit a pull request please? The share API was done by @tzafrir

**Comment by tzafrir** [comment]
The code in question here is _parsePost

**Comment by ryanpeggs** [comment]
Pull request submitted...

**Comment by mohamedmansour** [comment]
Awesome thanks Ryan! Fixed in #30
