### ISSUE TITLE
use it in a website ?

### ISSUE THREAD

**Issue by ManUtopiK** [mohamedmansour/google-plus-extension-jsapi#39]
Can we use this library in a website on client or server side ? Or this is only on a google chrome extension ?
I tried it, but _getSession doesn't work...

**Comment by tzafrir** [comment]
This won't work because of security restrictions. In a Chrome environment, you request explicit permission to access Google+ and can then get the session

**Comment by ManUtopiK** [comment]
Thank you for your fast reply !
This is due to x-domain restriction or internal chrome security ? Did you think it could be working with this cross domain ajax hack > [https://github.com/padolsey/jquery.fn/tree/master/cross-domain-ajax](https://github.com/padolsey/jquery.fn/tree/master/cross-domain-ajax) ?
(I think not, but I keep hope alive...)
